"""Phase 2 — BERTopic topics over the per-decade lyrics corpus.

Topics are discovered with **BERTopic** over the corpus built by
:mod:`src.lyrics.corpus`. Two views of each song are used the way the roadmap
locks them down:

* **embeddings** come from the natural ``text`` view, encoded with the Hungarian
  huBERT sentence-transformer. Songs longer than the model's 128-token window are
  split into ≤128-token chunks, each chunk embedded, then **mean-pooled** into one
  vector per song.
* the **count layer / c-TF-IDF** (topic keywords) is computed over the lemmatized
  ``tokens`` view (content words with bi/tri-grams folded by ``_``), by passing the
  joined-token strings as BERTopic's documents and a whitespace ``CountVectorizer``
  so the ``_``-joined n-grams survive intact.

Topic **names** are not generated by any LLM API: the build emits each topic's top
keywords to ``topic_info.json`` with a deterministic fallback name; a human-curated
``topic_names.json`` (authored by reading those keywords) is merged over it. Only
aggregate keywords ever leave the pipeline — never full lyrics (copyright).

Artifacts are cached as JSON under ``data/processed/topics/`` for the dashboard to
read without re-running the model. The pure helpers are doctested; the heavy
dependencies (bertopic, sentence-transformers, scikit-learn) are imported inside
functions so this module stays import-safe without the ``nlp-ml`` extra installed.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

from src.lyrics.corpus import SongDoc, load_corpus

if TYPE_CHECKING:
    import numpy as np

DEFAULT_TOPICS_DIR = Path("data/processed/topics")

# Hungarian-native huBERT sentence-transformer; 128-token windows (roadmap).
EMBED_MODEL = "NYTK/sentence-transformers-experimental-hubert-hungarian"
MAX_SEQ_LEN = 128
# Leave room for the [CLS]/[SEP] special tokens the model adds per chunk.
CHUNK_LEN = MAX_SEQ_LEN - 2

# Clustering knobs. huBERT embeddings of Hungarian lyrics sit in a tight,
# anisotropic cone (mean pairwise cosine ~0.55), so the default HDBSCAN dumps
# ~everything into one topic. ``leaf`` selection + cosine UMAP breaks that blob
# into coherent themes; outliers are then reassigned to their nearest topic.
UMAP_NEIGHBORS = 15
UMAP_COMPONENTS = 5
MIN_CLUSTER_SIZE = 60
TOP_KEYWORDS = 15


def joined_tokens(doc: SongDoc) -> str:
    """Join a song's lemma tokens into one whitespace-separated string.

    This is the document the c-TF-IDF vectorizer sees, so ``_``-joined n-grams
    (e.g. ``el_megy``) stay as single tokens under a whitespace analyzer.

    Args:
        doc: A corpus document.

    Returns:
        The tokens joined by single spaces.

    Examples:
        >>> from src.lyrics.corpus import SongDoc
        >>> joined_tokens(SongDoc(1, 1990, "x", ["szerelem", "el_megy"]))
        'szerelem el_megy'
        >>> joined_tokens(SongDoc(2, 2000, "y", []))
        ''
    """
    return " ".join(doc.tokens)


def chunk_token_ids(ids: list[int], max_len: int = CHUNK_LEN) -> list[list[int]]:
    """Split a token-id list into consecutive windows of at most ``max_len``.

    Args:
        ids: Token ids for one document.
        max_len: Maximum window length (must be positive).

    Returns:
        A list of windows; ``[[]]`` for empty input so the doc still yields one
        (empty) chunk to embed.

    Raises:
        ValueError: If ``max_len`` is not positive.

    Examples:
        >>> chunk_token_ids([1, 2, 3, 4, 5], max_len=2)
        [[1, 2], [3, 4], [5]]
        >>> chunk_token_ids([1, 2], max_len=5)
        [[1, 2]]
        >>> chunk_token_ids([])
        [[]]
    """
    if max_len <= 0:
        raise ValueError("max_len must be positive")
    if not ids:
        return [[]]
    return [ids[i : i + max_len] for i in range(0, len(ids), max_len)]


def fallback_name(keywords: list[str], k: int = 3) -> str:
    """Build a deterministic topic name from its top keywords.

    Used until a human-curated name is supplied.

    Args:
        keywords: Topic keywords, most representative first.
        k: How many to include.

    Returns:
        The top ``k`` keywords joined by ``' · '``, or ``'—'`` if none.

    Examples:
        >>> fallback_name(["szerelem", "szív", "csók", "vágy"])
        'szerelem · szív · csók'
        >>> fallback_name(["buli"], k=3)
        'buli'
        >>> fallback_name([])
        '—'
    """
    top = keywords[:k]
    return " · ".join(top) if top else "—"


def merge_names(
    info: list[dict[str, Any]], curated: dict[int, str]
) -> list[dict[str, Any]]:
    """Return ``info`` with curated names overriding the fallback names.

    Args:
        info: Topic records (each with ``topic_id`` and ``name``).
        curated: Map of topic id to human-authored name.

    Returns:
        New records with ``name`` replaced where a curated name exists.

    Examples:
        >>> info = [{"topic_id": 0, "name": "a · b"}, {"topic_id": 1, "name": "c"}]
        >>> merge_names(info, {0: "Szerelem"})
        [{'topic_id': 0, 'name': 'Szerelem'}, {'topic_id': 1, 'name': 'c'}]
        >>> merge_names(info, {})[0]["name"]
        'a · b'
    """
    out: list[dict[str, Any]] = []
    for rec in info:
        new = dict(rec)
        tid = new.get("topic_id")
        if isinstance(tid, int) and tid in curated:
            new["name"] = curated[tid]
        out.append(new)
    return out


def embed_documents(texts: list[str], model: Any) -> np.ndarray:
    """Embed each text by chunking to ≤128 tokens and mean-pooling the chunks.

    Args:
        texts: Natural-language song texts (the ``text`` view).
        model: A loaded ``sentence_transformers.SentenceTransformer``.

    Returns:
        An ``(len(texts), dim)`` float array, one mean-pooled vector per text.
    """
    import numpy as np

    tokenizer = model.tokenizer
    # Flatten every doc's chunks into one batch, tracking which doc each came from.
    chunk_texts: list[str] = []
    owners: list[int] = []
    for doc_idx, text in enumerate(texts):
        ids = tokenizer.encode(text or "", add_special_tokens=False)
        for window in chunk_token_ids(ids, CHUNK_LEN):
            chunk_texts.append(tokenizer.decode(window))
            owners.append(doc_idx)

    vecs = model.encode(chunk_texts, show_progress_bar=False, convert_to_numpy=True)
    dim = vecs.shape[1] if vecs.size else model.get_sentence_embedding_dimension()

    pooled = np.zeros((len(texts), dim), dtype=np.float32)
    counts = np.zeros(len(texts), dtype=np.int64)
    for vec, owner in zip(vecs, owners, strict=True):
        pooled[owner] += vec
        counts[owner] += 1
    counts = np.maximum(counts, 1)
    return pooled / counts[:, None]


def make_vectorizer(min_df: int = 2) -> Any:
    """Build the c-TF-IDF CountVectorizer for pre-tokenized lemma documents.

    Uses a whitespace analyzer so ``_``-joined n-grams are preserved verbatim and
    no extra lowercasing/regex splitting is applied (the tokens are already
    lemmatized and lowercased).

    Args:
        min_df: Minimum document frequency for a term to be kept.

    Returns:
        A configured ``sklearn.feature_extraction.text.CountVectorizer``.
    """
    from sklearn.feature_extraction.text import CountVectorizer

    return CountVectorizer(analyzer=str.split, min_df=min_df)


def compute_embeddings(docs: list[SongDoc]) -> np.ndarray:
    """Encode every song's natural text into one mean-pooled huBERT vector.

    Args:
        docs: The corpus.

    Returns:
        An ``(len(docs), dim)`` float array (see :func:`embed_documents`).
    """
    from sentence_transformers import SentenceTransformer

    embedder = SentenceTransformer(EMBED_MODEL)
    embedder.max_seq_length = MAX_SEQ_LEN
    return embed_documents([d.text for d in docs], embedder)


def build_topic_model(
    docs: list[SongDoc],
    embeddings: np.ndarray,
    *,
    min_cluster_size: int = MIN_CLUSTER_SIZE,
    reduce_outliers: bool = True,
) -> tuple[Any, list[int]]:
    """Fit BERTopic over the corpus (precomputed huBERT embeddings + lemma c-TF-IDF).

    The model embeds the natural-text view (via ``embeddings``) but vectorizes the
    lemma ``tokens`` view for c-TF-IDF keywords. ``language="multilingual"`` is
    essential: BERTopic's English preprocessing strips every non-ASCII character,
    which would mangle Hungarian (``szép`` → ``szp``) and drop ``_`` n-grams.

    Args:
        docs: The corpus, in embedding order.
        embeddings: Precomputed per-song vectors (see :func:`compute_embeddings`).
        min_cluster_size: HDBSCAN minimum cluster size.
        reduce_outliers: Reassign ``-1`` docs to their nearest topic for coverage.

    Returns:
        ``(topic_model, topics)`` where ``topics`` is the per-doc topic assignment.
    """
    from bertopic import BERTopic
    from hdbscan import HDBSCAN
    from umap import UMAP

    umap_model = UMAP(
        n_neighbors=UMAP_NEIGHBORS,
        n_components=UMAP_COMPONENTS,
        min_dist=0.0,
        metric="cosine",
        random_state=42,
    )
    hdbscan_model = HDBSCAN(
        min_cluster_size=min_cluster_size,
        metric="euclidean",
        cluster_selection_method="leaf",
        prediction_data=True,
    )
    documents = [joined_tokens(d) for d in docs]
    topic_model = BERTopic(
        language="multilingual",
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=make_vectorizer(),
        calculate_probabilities=False,
        verbose=False,
    )
    topics, _ = topic_model.fit_transform(documents, embeddings=embeddings)

    if reduce_outliers and -1 in topics:
        topics = topic_model.reduce_outliers(
            documents, list(topics), strategy="c-tf-idf"
        )
        topic_model.update_topics(
            documents, topics=topics, vectorizer_model=make_vectorizer()
        )
    return topic_model, list(topics)


def topic_info(topic_model: Any) -> list[dict[str, Any]]:
    """Extract a JSON-able topic table with fallback names.

    Args:
        topic_model: A fitted BERTopic model.

    Returns:
        One record per topic: ``{topic_id, size, keywords, name}``. Keywords are
        aggregate c-TF-IDF terms only — never raw lyrics.
    """
    info = topic_model.get_topic_info()
    records: list[dict[str, Any]] = []
    for row in info.itertuples():
        tid = int(row.Topic)
        terms = topic_model.get_topic(tid) or []
        keywords = [term for term, _score in terms[:TOP_KEYWORDS]]
        records.append(
            {
                "topic_id": tid,
                "size": int(row.Count),
                "keywords": keywords,
                "name": fallback_name(keywords),
            }
        )
    return records


def topics_over_time(
    topic_model: Any, docs: list[SongDoc]
) -> list[dict[str, int | float]]:
    """Compute per-(topic, decade) frequencies for the over-time chart.

    Args:
        topic_model: A fitted BERTopic model.
        docs: The same corpus passed to :func:`build_topic_model`, in order.

    Returns:
        Records ``{topic_id, decade, frequency}`` (one per topic/decade cell).
    """
    documents = [joined_tokens(d) for d in docs]
    timestamps = [d.decade for d in docs]
    frame = topic_model.topics_over_time(documents, timestamps)
    return [
        {
            "topic_id": int(row.Topic),
            "decade": int(row.Timestamp),
            "frequency": int(row.Frequency),
        }
        for row in frame.itertuples()
    ]


def load_topic_names(path: Path | str) -> dict[int, str]:
    """Load the human-curated ``topic_names.json`` (string keys → int).

    Args:
        path: Path to the curated names JSON (``{"0": "Szerelem", ...}``).

    Returns:
        Map of topic id to curated name; empty if the file is missing.
    """
    p = Path(path)
    if not p.exists():
        return {}
    raw = json.loads(p.read_text(encoding="utf-8"))
    return {int(k): str(v) for k, v in raw.items()}


def save_artifacts(
    info: list[dict[str, Any]],
    over_time: list[dict[str, int | float]],
    out_dir: Path | str = DEFAULT_TOPICS_DIR,
) -> None:
    """Write the topic artifacts as JSON under ``out_dir``.

    Args:
        info: Topic table from :func:`topic_info` (curated names merged in).
        over_time: Records from :func:`topics_over_time`.
        out_dir: Output directory (created if missing).
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "topic_info.json").write_text(
        json.dumps(info, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (out / "topics_over_time.json").write_text(
        json.dumps(over_time, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def main() -> None:
    """Build topics from the cached corpus and write JSON artifacts.

    Embeddings are cached to ``<out-dir>/embeddings.npy`` so re-runs (e.g. to
    re-tune clustering or merge curated names) skip the slow huBERT pass. Delete
    that file or pass ``--reembed`` to force re-encoding.
    """
    import argparse

    import numpy as np

    parser = argparse.ArgumentParser(description="Build BERTopic topics over decades.")
    parser.add_argument(
        "--corpus-dir", default="data/processed/corpus", help="corpus JSONL dir"
    )
    parser.add_argument("--out-dir", default=str(DEFAULT_TOPICS_DIR))
    parser.add_argument("--min-cluster-size", type=int, default=MIN_CLUSTER_SIZE)
    parser.add_argument("--reembed", action="store_true", help="force re-embedding")
    args = parser.parse_args()

    docs = load_corpus(args.corpus_dir)
    if not docs:
        raise SystemExit(f"No corpus docs in {args.corpus_dir}; build it first.")

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    emb_path = out / "embeddings.npy"
    if emb_path.exists() and not args.reembed:
        embeddings = np.load(emb_path)
        if len(embeddings) != len(docs):  # corpus changed → re-embed
            embeddings = compute_embeddings(docs)
            np.save(emb_path, embeddings)
    else:
        embeddings = compute_embeddings(docs)
        np.save(emb_path, embeddings)

    topic_model, _ = build_topic_model(
        docs, embeddings, min_cluster_size=args.min_cluster_size
    )
    info = topic_info(topic_model)
    over_time = topics_over_time(topic_model, docs)

    curated = load_topic_names(out / "topic_names.json")
    info = merge_names(info, curated)
    save_artifacts(info, over_time, args.out_dir)

    n_topics = sum(1 for r in info if r["topic_id"] != -1)
    print(f"Built {n_topics} topics from {len(docs)} docs -> {args.out_dir}")
    print(f"  curated names merged: {len(curated)}")


if __name__ == "__main__":
    main()
